version: '2'
services:
    api:
        build: .
        ports:
            - "5000:5000"
        environment:
            - REPORTER_SERVICE_HOSTNAME='your_ip_address_or_hostname'
        depends_on:
            - mongodb
    mongodb:
        image: bitnami/mongodb:latest
        container_name: reporter_db
        ports:
            - "27017:27017"
        volumes:
            - 'your_volume_here'
